// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casbin.proto

// Protobuf Java Version: 3.25.0
package com.github.saturn_xiv.palm.plugins.casbin.v1;

public interface BoolReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.lily.v1.BoolReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool res = 1;</code>
   * @return The res.
   */
  boolean getRes();
}
