// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casbin.proto

// Protobuf Java Version: 3.25.0
package com.github.saturn_xiv.palm.plugins.casbin.v1;

public final class CasbinProto {
  private CasbinProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_NewEnforcerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_NewEnforcerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_NewEnforcerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_NewEnforcerReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_NewAdapterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_NewAdapterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_NewAdapterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_NewAdapterReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_EnforceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_EnforceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_BoolReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_BoolReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_EmptyReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_EmptyReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_PolicyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_PolicyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_SimpleGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_SimpleGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_ArrayReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_ArrayReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_FilteredPolicyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_FilteredPolicyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_UserRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_UserRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_PermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_PermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_Array2DReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_Array2DReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_palm_lily_v1_Array2DReply_d_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_palm_lily_v1_Array2DReply_d_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014casbin.proto\022\014palm.lily.v1\">\n\022NewEnfor" +
      "cerRequest\022\021\n\tmodelText\030\001 \001(\t\022\025\n\radapter" +
      "Handle\030\002 \001(\005\"#\n\020NewEnforcerReply\022\017\n\007hand" +
      "ler\030\001 \001(\005\"h\n\021NewAdapterRequest\022\023\n\013adapte" +
      "rName\030\001 \001(\t\022\022\n\ndriverName\030\002 \001(\t\022\025\n\rconne" +
      "ctString\030\003 \001(\t\022\023\n\013dbSpecified\030\004 \001(\010\"\"\n\017N" +
      "ewAdapterReply\022\017\n\007handler\030\001 \001(\005\"9\n\016Enfor" +
      "ceRequest\022\027\n\017enforcerHandler\030\001 \001(\005\022\016\n\006pa" +
      "rams\030\002 \003(\t\"\030\n\tBoolReply\022\013\n\003res\030\001 \001(\010\"\037\n\014" +
      "EmptyRequest\022\017\n\007handler\030\001 \001(\005\"\014\n\nEmptyRe" +
      "ply\"G\n\rPolicyRequest\022\027\n\017enforcerHandler\030" +
      "\001 \001(\005\022\r\n\005pType\030\002 \001(\t\022\016\n\006params\030\003 \003(\t\":\n\020" +
      "SimpleGetRequest\022\027\n\017enforcerHandler\030\001 \001(" +
      "\005\022\r\n\005pType\030\002 \001(\t\"\033\n\nArrayReply\022\r\n\005array\030" +
      "\001 \003(\t\"h\n\025FilteredPolicyRequest\022\027\n\017enforc" +
      "erHandler\030\001 \001(\005\022\r\n\005pType\030\002 \001(\t\022\022\n\nfieldI" +
      "ndex\030\003 \001(\005\022\023\n\013fieldValues\030\004 \003(\t\"V\n\017UserR" +
      "oleRequest\022\027\n\017enforcerHandler\030\001 \001(\005\022\014\n\004u" +
      "ser\030\002 \001(\t\022\014\n\004role\030\003 \001(\t\022\016\n\006domain\030\004 \003(\t\"" +
      "_\n\021PermissionRequest\022\027\n\017enforcerHandler\030" +
      "\001 \001(\005\022\014\n\004user\030\002 \001(\t\022\023\n\013permissions\030\003 \003(\t" +
      "\022\016\n\006domain\030\004 \003(\t\"I\n\014Array2DReply\022(\n\002d2\030\001" +
      " \003(\0132\034.palm.lily.v1.Array2DReply.d\032\017\n\001d\022" +
      "\n\n\002d1\030\001 \003(\t2\211\"\n\006Casbin\022Q\n\013NewEnforcer\022 ." +
      "palm.lily.v1.NewEnforcerRequest\032\036.palm.l" +
      "ily.v1.NewEnforcerReply\"\000\022N\n\nNewAdapter\022" +
      "\037.palm.lily.v1.NewAdapterRequest\032\035.palm." +
      "lily.v1.NewAdapterReply\"\000\022B\n\007Enforce\022\034.p" +
      "alm.lily.v1.EnforceRequest\032\027.palm.lily.v" +
      "1.BoolReply\"\000\022D\n\nLoadPolicy\022\032.palm.lily." +
      "v1.EmptyRequest\032\030.palm.lily.v1.EmptyRepl" +
      "y\"\000\022D\n\nSavePolicy\022\032.palm.lily.v1.EmptyRe" +
      "quest\032\030.palm.lily.v1.EmptyReply\"\000\022C\n\tAdd" +
      "Policy\022\033.palm.lily.v1.PolicyRequest\032\027.pa" +
      "lm.lily.v1.BoolReply\"\000\022H\n\016AddNamedPolicy" +
      "\022\033.palm.lily.v1.PolicyRequest\032\027.palm.lil" +
      "y.v1.BoolReply\"\000\022F\n\014RemovePolicy\022\033.palm." +
      "lily.v1.PolicyRequest\032\027.palm.lily.v1.Boo" +
      "lReply\"\000\022K\n\021RemoveNamedPolicy\022\033.palm.lil" +
      "y.v1.PolicyRequest\032\027.palm.lily.v1.BoolRe" +
      "ply\"\000\022V\n\024RemoveFilteredPolicy\022#.palm.lil" +
      "y.v1.FilteredPolicyRequest\032\027.palm.lily.v" +
      "1.BoolReply\"\000\022[\n\031RemoveFilteredNamedPoli" +
      "cy\022#.palm.lily.v1.FilteredPolicyRequest\032" +
      "\027.palm.lily.v1.BoolReply\"\000\022E\n\tGetPolicy\022" +
      "\032.palm.lily.v1.EmptyRequest\032\032.palm.lily." +
      "v1.Array2DReply\"\000\022K\n\016GetNamedPolicy\022\033.pa" +
      "lm.lily.v1.PolicyRequest\032\032.palm.lily.v1." +
      "Array2DReply\"\000\022V\n\021GetFilteredPolicy\022#.pa" +
      "lm.lily.v1.FilteredPolicyRequest\032\032.palm." +
      "lily.v1.Array2DReply\"\000\022[\n\026GetFilteredNam" +
      "edPolicy\022#.palm.lily.v1.FilteredPolicyRe" +
      "quest\032\032.palm.lily.v1.Array2DReply\"\000\022K\n\021A" +
      "ddGroupingPolicy\022\033.palm.lily.v1.PolicyRe" +
      "quest\032\027.palm.lily.v1.BoolReply\"\000\022P\n\026AddN" +
      "amedGroupingPolicy\022\033.palm.lily.v1.Policy" +
      "Request\032\027.palm.lily.v1.BoolReply\"\000\022N\n\024Re" +
      "moveGroupingPolicy\022\033.palm.lily.v1.Policy" +
      "Request\032\027.palm.lily.v1.BoolReply\"\000\022S\n\031Re" +
      "moveNamedGroupingPolicy\022\033.palm.lily.v1.P" +
      "olicyRequest\032\027.palm.lily.v1.BoolReply\"\000\022" +
      "^\n\034RemoveFilteredGroupingPolicy\022#.palm.l" +
      "ily.v1.FilteredPolicyRequest\032\027.palm.lily" +
      ".v1.BoolReply\"\000\022c\n!RemoveFilteredNamedGr" +
      "oupingPolicy\022#.palm.lily.v1.FilteredPoli" +
      "cyRequest\032\027.palm.lily.v1.BoolReply\"\000\022M\n\021" +
      "GetGroupingPolicy\022\032.palm.lily.v1.EmptyRe" +
      "quest\032\032.palm.lily.v1.Array2DReply\"\000\022S\n\026G" +
      "etNamedGroupingPolicy\022\033.palm.lily.v1.Pol" +
      "icyRequest\032\032.palm.lily.v1.Array2DReply\"\000" +
      "\022^\n\031GetFilteredGroupingPolicy\022#.palm.lil" +
      "y.v1.FilteredPolicyRequest\032\032.palm.lily.v" +
      "1.Array2DReply\"\000\022c\n\036GetFilteredNamedGrou" +
      "pingPolicy\022#.palm.lily.v1.FilteredPolicy" +
      "Request\032\032.palm.lily.v1.Array2DReply\"\000\022H\n" +
      "\016GetAllSubjects\022\032.palm.lily.v1.EmptyRequ" +
      "est\032\030.palm.lily.v1.ArrayReply\"\000\022Q\n\023GetAl" +
      "lNamedSubjects\022\036.palm.lily.v1.SimpleGetR" +
      "equest\032\030.palm.lily.v1.ArrayReply\"\000\022G\n\rGe" +
      "tAllObjects\022\032.palm.lily.v1.EmptyRequest\032" +
      "\030.palm.lily.v1.ArrayReply\"\000\022P\n\022GetAllNam" +
      "edObjects\022\036.palm.lily.v1.SimpleGetReques" +
      "t\032\030.palm.lily.v1.ArrayReply\"\000\022G\n\rGetAllA" +
      "ctions\022\032.palm.lily.v1.EmptyRequest\032\030.pal" +
      "m.lily.v1.ArrayReply\"\000\022P\n\022GetAllNamedAct" +
      "ions\022\036.palm.lily.v1.SimpleGetRequest\032\030.p" +
      "alm.lily.v1.ArrayReply\"\000\022E\n\013GetAllRoles\022" +
      "\032.palm.lily.v1.EmptyRequest\032\030.palm.lily." +
      "v1.ArrayReply\"\000\022N\n\020GetAllNamedRoles\022\036.pa" +
      "lm.lily.v1.SimpleGetRequest\032\030.palm.lily." +
      "v1.ArrayReply\"\000\022C\n\tHasPolicy\022\033.palm.lily" +
      ".v1.PolicyRequest\032\027.palm.lily.v1.BoolRep" +
      "ly\"\000\022H\n\016HasNamedPolicy\022\033.palm.lily.v1.Po" +
      "licyRequest\032\027.palm.lily.v1.BoolReply\"\000\022K" +
      "\n\021HasGroupingPolicy\022\033.palm.lily.v1.Polic" +
      "yRequest\032\027.palm.lily.v1.BoolReply\"\000\022P\n\026H" +
      "asNamedGroupingPolicy\022\033.palm.lily.v1.Pol" +
      "icyRequest\032\027.palm.lily.v1.BoolReply\"\000\022G\n" +
      "\nGetDomains\022\035.palm.lily.v1.UserRoleReque" +
      "st\032\030.palm.lily.v1.ArrayReply\"\000\022L\n\017GetRol" +
      "esForUser\022\035.palm.lily.v1.UserRoleRequest" +
      "\032\030.palm.lily.v1.ArrayReply\"\000\022T\n\027GetImpli" +
      "citRolesForUser\022\035.palm.lily.v1.UserRoleR" +
      "equest\032\030.palm.lily.v1.ArrayReply\"\000\022L\n\017Ge" +
      "tUsersForRole\022\035.palm.lily.v1.UserRoleReq" +
      "uest\032\030.palm.lily.v1.ArrayReply\"\000\022J\n\016HasR" +
      "oleForUser\022\035.palm.lily.v1.UserRoleReques" +
      "t\032\027.palm.lily.v1.BoolReply\"\000\022J\n\016AddRoleF" +
      "orUser\022\035.palm.lily.v1.UserRoleRequest\032\027." +
      "palm.lily.v1.BoolReply\"\000\022M\n\021DeleteRoleFo" +
      "rUser\022\035.palm.lily.v1.UserRoleRequest\032\027.p" +
      "alm.lily.v1.BoolReply\"\000\022N\n\022DeleteRolesFo" +
      "rUser\022\035.palm.lily.v1.UserRoleRequest\032\027.p" +
      "alm.lily.v1.BoolReply\"\000\022F\n\nDeleteUser\022\035." +
      "palm.lily.v1.UserRoleRequest\032\027.palm.lily" +
      ".v1.BoolReply\"\000\022G\n\nDeleteRole\022\035.palm.lil" +
      "y.v1.UserRoleRequest\032\030.palm.lily.v1.Empt" +
      "yReply\"\000\022V\n\025GetPermissionsForUser\022\037.palm" +
      ".lily.v1.PermissionRequest\032\032.palm.lily.v" +
      "1.Array2DReply\"\000\022^\n\035GetImplicitPermissio" +
      "nsForUser\022\037.palm.lily.v1.PermissionReque" +
      "st\032\032.palm.lily.v1.Array2DReply\"\000\022N\n\020Dele" +
      "tePermission\022\037.palm.lily.v1.PermissionRe" +
      "quest\032\027.palm.lily.v1.BoolReply\"\000\022R\n\024AddP" +
      "ermissionForUser\022\037.palm.lily.v1.Permissi" +
      "onRequest\032\027.palm.lily.v1.BoolReply\"\000\022U\n\027" +
      "DeletePermissionForUser\022\037.palm.lily.v1.P" +
      "ermissionRequest\032\027.palm.lily.v1.BoolRepl" +
      "y\"\000\022V\n\030DeletePermissionsForUser\022\037.palm.l" +
      "ily.v1.PermissionRequest\032\027.palm.lily.v1." +
      "BoolReply\"\000\022R\n\024HasPermissionForUser\022\037.pa" +
      "lm.lily.v1.PermissionRequest\032\027.palm.lily" +
      ".v1.BoolReply\"\000BX\n,com.github.saturn_xiv" +
      ".palm.plugins.casbin.v1B\013CasbinProtoP\001Z\010" +
      "./;proto\252\002\016CasbinOrg.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_palm_lily_v1_NewEnforcerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_palm_lily_v1_NewEnforcerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_NewEnforcerRequest_descriptor,
        new java.lang.String[] { "ModelText", "AdapterHandle", });
    internal_static_palm_lily_v1_NewEnforcerReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_palm_lily_v1_NewEnforcerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_NewEnforcerReply_descriptor,
        new java.lang.String[] { "Handler", });
    internal_static_palm_lily_v1_NewAdapterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_palm_lily_v1_NewAdapterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_NewAdapterRequest_descriptor,
        new java.lang.String[] { "AdapterName", "DriverName", "ConnectString", "DbSpecified", });
    internal_static_palm_lily_v1_NewAdapterReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_palm_lily_v1_NewAdapterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_NewAdapterReply_descriptor,
        new java.lang.String[] { "Handler", });
    internal_static_palm_lily_v1_EnforceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_palm_lily_v1_EnforceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_EnforceRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "Params", });
    internal_static_palm_lily_v1_BoolReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_palm_lily_v1_BoolReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_BoolReply_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_palm_lily_v1_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_palm_lily_v1_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_EmptyRequest_descriptor,
        new java.lang.String[] { "Handler", });
    internal_static_palm_lily_v1_EmptyReply_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_palm_lily_v1_EmptyReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_EmptyReply_descriptor,
        new java.lang.String[] { });
    internal_static_palm_lily_v1_PolicyRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_palm_lily_v1_PolicyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_PolicyRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "PType", "Params", });
    internal_static_palm_lily_v1_SimpleGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_palm_lily_v1_SimpleGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_SimpleGetRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "PType", });
    internal_static_palm_lily_v1_ArrayReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_palm_lily_v1_ArrayReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_ArrayReply_descriptor,
        new java.lang.String[] { "Array", });
    internal_static_palm_lily_v1_FilteredPolicyRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_palm_lily_v1_FilteredPolicyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_FilteredPolicyRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "PType", "FieldIndex", "FieldValues", });
    internal_static_palm_lily_v1_UserRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_palm_lily_v1_UserRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_UserRoleRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "User", "Role", "Domain", });
    internal_static_palm_lily_v1_PermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_palm_lily_v1_PermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_PermissionRequest_descriptor,
        new java.lang.String[] { "EnforcerHandler", "User", "Permissions", "Domain", });
    internal_static_palm_lily_v1_Array2DReply_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_palm_lily_v1_Array2DReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_Array2DReply_descriptor,
        new java.lang.String[] { "D2", });
    internal_static_palm_lily_v1_Array2DReply_d_descriptor =
      internal_static_palm_lily_v1_Array2DReply_descriptor.getNestedTypes().get(0);
    internal_static_palm_lily_v1_Array2DReply_d_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_palm_lily_v1_Array2DReply_d_descriptor,
        new java.lang.String[] { "D1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
