// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casbin.proto

// Protobuf Java Version: 3.25.0
package com.github.saturn_xiv.palm.plugins.casbin.v1;

public interface EmptyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.lily.v1.EmptyReply)
    com.google.protobuf.MessageOrBuilder {
}
