// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: casbin.proto

// Protobuf Java Version: 3.25.0
package com.github.saturn_xiv.palm.plugins.casbin.v1;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.lily.v1.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 handler = 1;</code>
   * @return The handler.
   */
  int getHandler();
}
