# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: casbin.proto for package 'palm.lily.v1'
# Original file comments:
# Copyright 2018 The casbin Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'casbin_pb'

module Palm
  module Lily
    module V1
      module Casbin
        # The Casbin service definition.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'palm.lily.v1.Casbin'

          rpc :NewEnforcer, ::Palm::Lily::V1::NewEnforcerRequest, ::Palm::Lily::V1::NewEnforcerReply
          rpc :NewAdapter, ::Palm::Lily::V1::NewAdapterRequest, ::Palm::Lily::V1::NewAdapterReply
          rpc :Enforce, ::Palm::Lily::V1::EnforceRequest, ::Palm::Lily::V1::BoolReply
          rpc :LoadPolicy, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::EmptyReply
          rpc :SavePolicy, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::EmptyReply
          rpc :AddPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :AddNamedPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemovePolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveNamedPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveFilteredPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveFilteredNamedPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :GetPolicy, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetNamedPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetFilteredPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetFilteredNamedPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :AddGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :AddNamedGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveNamedGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveFilteredGroupingPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :RemoveFilteredNamedGroupingPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :GetGroupingPolicy, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetNamedGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetFilteredGroupingPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetFilteredNamedGroupingPolicy, ::Palm::Lily::V1::FilteredPolicyRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetAllSubjects, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllNamedSubjects, ::Palm::Lily::V1::SimpleGetRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllObjects, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllNamedObjects, ::Palm::Lily::V1::SimpleGetRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllActions, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllNamedActions, ::Palm::Lily::V1::SimpleGetRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllRoles, ::Palm::Lily::V1::EmptyRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetAllNamedRoles, ::Palm::Lily::V1::SimpleGetRequest, ::Palm::Lily::V1::ArrayReply
          rpc :HasPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :HasNamedPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :HasGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :HasNamedGroupingPolicy, ::Palm::Lily::V1::PolicyRequest, ::Palm::Lily::V1::BoolReply
          rpc :GetDomains, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetRolesForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetImplicitRolesForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::ArrayReply
          rpc :GetUsersForRole, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::ArrayReply
          rpc :HasRoleForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::BoolReply
          rpc :AddRoleForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeleteRoleForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeleteRolesForUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeleteUser, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeleteRole, ::Palm::Lily::V1::UserRoleRequest, ::Palm::Lily::V1::EmptyReply
          rpc :GetPermissionsForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::Array2DReply
          rpc :GetImplicitPermissionsForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::Array2DReply
          rpc :DeletePermission, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::BoolReply
          rpc :AddPermissionForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeletePermissionForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::BoolReply
          rpc :DeletePermissionsForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::BoolReply
          rpc :HasPermissionForUser, ::Palm::Lily::V1::PermissionRequest, ::Palm::Lily::V1::BoolReply
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
